// GENERATED by tools/flight/export_site.py from flight_v2.mp4 and tools/flight/pins.json. Do not edit.
export type StopId = 'river' | 'brickell' | 'downtown' | 'bay' | 'beach' | 'sunset';

export interface FlightStop {
  id: StopId;
  frame: number;
  x: number;
  y: number;
  phoneX: number;
  place: string;
  coords: string;
}

export const flight: { frames: number; width: number; height: number; phoneWidth: number; stops: FlightStop[] } = {
  "frames": 413,
  "width": 1280,
  "height": 704,
  "phoneWidth": 420,
  "stops": [
    {
      "id": "river",
      "frame": 40,
      "x": 0.59,
      "y": 0.3,
      "place": "River",
      "coords": "25.770° N · 80.189° W",
      "phoneX": 0.5005
    },
    {
      "id": "brickell",
      "frame": 114,
      "x": 0.64,
      "y": 0.3,
      "place": "Brickell",
      "coords": "25.759° N · 80.194° W",
      "phoneX": 0.5005
    },
    {
      "id": "downtown",
      "frame": 189,
      "x": 0.65,
      "y": 0.28,
      "place": "Downtown",
      "coords": "25.774° N · 80.194° W",
      "phoneX": 0.5
    },
    {
      "id": "bay",
      "frame": 264,
      "x": 0.56,
      "y": 0.42,
      "place": "The Bay",
      "coords": "25.790° N · 80.170° W",
      "phoneX": 0.5019
    },
    {
      "id": "beach",
      "frame": 338,
      "x": 0.63,
      "y": 0.3,
      "place": "The Beach",
      "coords": "25.790° N · 80.130° W",
      "phoneX": 0.501
    },
    {
      "id": "sunset",
      "frame": 412,
      "x": 0.505,
      "y": 0.465,
      "place": "Sunset",
      "coords": "25.785° N · 80.100° W",
      "phoneX": 0.501
    }
  ]
};
