"""Exports flight v2 into the site: desktop and phone frame sets plus src/flight/flightData.ts.

Usage (ComfyUI embedded Python): python export_site.py <repo_root>
Reads output/video/flight/flight_v2.mp4 + flight_v2.json and tools/flight/pins.json.
Phone frames are a PHONE_W-wide crop around the landmark (interpolated between stops) at full height,
so portrait phones keep desktop sharpness at about a third of the bytes.
"""
import json
import os
import sys

import av

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))  # the embedded Python doesn't add the script's folder
from heal_chain import COMFY  # noqa: E402

STRIDE = 2
PHONE_W = 420

here = os.path.dirname(os.path.abspath(__file__))
root = sys.argv[1]
film = os.path.join(COMFY, 'output', 'video', 'flight', 'flight_v2.mp4')
meta = json.load(open(os.path.join(COMFY, 'output', 'video', 'flight', 'flight_v2.json')))
pins = json.load(open(os.path.join(here, 'pins.json'), encoding='utf8'))

stops = [{'id': pins[s['id']]['key'], 'frame': round(s['frame'] / STRIDE), 'x': pins[s['id']]['x'],
          'y': pins[s['id']]['y'], 'place': pins[s['id']]['place'], 'coords': pins[s['id']]['coords']}
         for s in meta['stops']]


def focal_x(i):
    if i <= stops[0]['frame']:
        return stops[0]['x']
    for a, b in zip(stops, stops[1:]):
        if i <= b['frame']:
            t = (i - a['frame']) / (b['frame'] - a['frame'])
            return a['x'] + (b['x'] - a['x']) * t
    return stops[-1]['x']


desktop = os.path.join(root, 'public', 'flight', 'desktop')
phone = os.path.join(root, 'public', 'flight', 'phone')
for d in (desktop, phone):
    os.makedirs(d, exist_ok=True)
    for old in os.listdir(d):
        os.remove(os.path.join(d, old))

crops, n, size = [], 0, None
for k, frame in enumerate(av.open(film).decode(video=0)):
    if k % STRIDE:
        continue
    img = frame.to_image()
    size = img.size
    img.save(os.path.join(desktop, f'f{n:03d}.webp'), quality=72, method=6)
    left = int(min(max(focal_x(n) * size[0] - PHONE_W / 2, 0), size[0] - PHONE_W))
    img.crop((left, 0, left + PHONE_W, size[1])).save(os.path.join(phone, f'f{n:03d}.webp'), quality=74, method=6)
    crops.append(left)
    n += 1

for s in stops:
    s['phoneX'] = round((s['x'] * size[0] - crops[s['frame']]) / PHONE_W, 4)

data = {'frames': n, 'width': size[0], 'height': size[1], 'phoneWidth': PHONE_W, 'stops': stops}
ts = (
    '// GENERATED by tools/flight/export_site.py from flight_v2.mp4 and tools/flight/pins.json. Do not edit.\n'
    "export type StopId = 'river' | 'brickell' | 'downtown' | 'bay' | 'beach' | 'sunset';\n\n"
    'export interface FlightStop {\n  id: StopId;\n  frame: number;\n  x: number;\n  y: number;\n'
    '  phoneX: number;\n  place: string;\n  coords: string;\n}\n\n'
    'export const flight: { frames: number; width: number; height: number; phoneWidth: number; stops: FlightStop[] } = '
    + json.dumps(data, ensure_ascii=False, indent=2) + ';\n'
)
open(os.path.join(root, 'src', 'flight', 'flightData.ts'), 'w', encoding='utf8').write(ts)
bytes_d = sum(os.path.getsize(os.path.join(desktop, f)) for f in os.listdir(desktop))
bytes_p = sum(os.path.getsize(os.path.join(phone, f)) for f in os.listdir(phone))
print(f'EXPORTED {n} frames: desktop {bytes_d / 1e6:.1f} MB, phone {bytes_p / 1e6:.1f} MB; stops {[s["frame"] for s in stops]}')
